---
- name: Initial playbook
  hosts: ansible-workshop
  tasks:
    - name: Install nginx
      apt: name=nginx state=present

    - name: Verify that nginx is started
      service: name=nginx state=started

    - name: Validate that nginx is running
      uri: url=http://localhost method=HEAD
