---
- name: Initial playbook
  hosts: ansible-workshop
  tasks:
    - name: Install nginx on Ubuntu/Debian
      apt:  name=nginx state=present
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RedHat/CentOS
      yum:  name=nginx state=present
      when: ansible_os_family == "RedHat"

    - name: Verify that nginx is started
      service: name=nginx state=started

    - name: Validate that nginx is running
      uri:  url=http://localhost method=HEAD
